### ISSUE TITLE
Provide browser bundle

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-stats#1]
It would be cool if it provided prebuilt browser bundle that can be embedded via `<script>`.  
(low priority, just nice to have)

See how we did it for `is-ipfs` before:
- https://github.com/ipfs/is-ipfs/issues/7
- https://github.com/ipfs/is-ipfs/issues/8

**Comment by hacdias** [comment]
I will work on this 🛩

**Comment by hacdias** [comment]
Just added aegir. When I close #2, I'll publish a browser bundle and update the readme.

**Comment by hacdias** [comment]
@lidel [done!](https://github.com/ipfs-shipyard/ipfs-stats#in-the-browser-through-script-tag)
