### ISSUE TITLE
Move this lib to ipfs or ipfs-shipyard

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-stats#2]
Rationale: this small lib will be used by both Desktop (https://github.com/ipfs-shipyard/ipfs-desktop/pull/595) and Companion (https://github.com/ipfs-shipyard/ipfs-companion/issues/358).

I say 👍  for moving it under ipfs/shipyard umbrella: we already did something similar with community-contributed https://github.com/ipfs/is-ipfs

But it is late here, so let's ping @diasdavid for a quick sanity check ;)

**Comment by daviddias** [comment]
go for it :)

**Comment by hacdias** [comment]
To ipfs or ipfs-shipyard?

@lidel @diasdavid this small lib also uses another lib ([ipfs-locations](https://github.com/hacdias/ipfs-locations)) to download the locations sequentially to improve performance. What was happening was that Desktop was making hundreds of requests at the same time and it could reduce performance. Should I move this one too?

**Comment by daviddias** [comment]
To `ipfs-shipyard`. Soon `ipfs` will just be for core pieces of the protocol stack and/or community+pm repos.

Also moved is-ipfs https://github.com/ipfs-shipyard/is-ipfs
